config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'} 
  resources :events
  resources :invitations
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :user_invites, class_name: "Invitation", foreign_key: :event_id
  has_many :attendees, through: :user_invites, source: :invitee

  has_one_attached :image
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invitee, class_name: "User"
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: "Event", foreign_key: :creator_id
  has_many :event_invites, class_name: "Invitation", foreign_key: :invitee_id
  has_many :attended_events, through: :event_invites, source: :event

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all.order("created_at ASC")
    @event = Event.new
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def rsvp 
    @event = event.find(params[:id])
    @event.attendees << current_user
    redirect_to @event
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :location, :image)
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  # before_action :set_invitation, only: %i[ show edit update destroy ]

  # GET /invitations or /invitations.json
  def index
    @invitations = Invitation.all
  end

  # GET /invitations/1 or /invitations/1.json
  def show
  end

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # GET /invitations/1/edit
  def edit
  end

  # POST /invitations or /invitations.json
  def create
    event = Event.find(params[:event_id])
    @invitation = Invitation.new(event_id: event.id, invitee_id: current_user.id)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to event_path(event), notice: "RSVP successful!" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { redirect_to event_path(event), notice: "RSVP FAILED!" }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invitations/1 or /invitations/1.json
  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to @invitation, notice: "RSVP was successfully updated." }
        format.json { render :show, status: :ok, location: @invitation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1 or /invitations/1.json
  def destroy
    event = Event.find(params[:event_id])
    @invitation = Invitation.find_by(event_id: event.id, invitee_id: current_user.id)
    @invitation.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "RSVP Cancelled." }
      format.json { head :no_content }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
    def sign_up_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitation_helper.rb
module InvitationHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/events/_form.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
      <h2 class="title is-2">New Event</h2>
      <%= simple_form_for(@event) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="field">
          <div class="control">
          <%= f.input :title, label: "Event Title:"%>
          </div>
        </div>

        <div class="field">
          <div class="control">
          <%= f.input :location, label: "Event Location:"%>
          </div>
        </div>

        <div class="field">
          <div class="control">
          <%= f.file_field :image %>
          </div>
        </div>
        
        <div class="field">
          <div class="control">
          <%= f.button :submit, "Create!", class:"button"%>
          </div>
        </div>

        

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="container is-centered">
  <%# <h1 class="title is-2 has-text-centered">Events</h1> %>
  <div class="columns is-multiline">
  <% @events.each do | event | %>
    <div class="column is-one-third has-text-centered">
      <%= link_to event do %>
        <% if event.image.attached? %>
          <%= image_tag event.image.variant(resize_to_limit: [500, 500]) %>
        <% else %>
          <img src="https://www.eduprizeschools.net/wp-content/uploads/2016/06/No_Image_Available.jpg">
        <% end %>
      <% end %>
      <strong><%= event.title %> @ <%=event.location %></strong>
    </div>
  <% end %>
  </div>
</div>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="container is-centered">
    <p class="content has-text-centered">
      <% if @event.image.attached? %>
        <%= image_tag @event.image.variant(resize_to_limit: [500, 500]) %>
      <% else %>
        <img class="image" src="https://www.eduprizeschools.net/wp-content/uploads/2016/06/No_Image_Available.jpg">
      <% end %>
      <br></br>
      <strong><%= @event.title %> @ <%= @event.location%></strong>
      <br></br>
      <a class="control"></a>
        <% if user_signed_in? && current_user.id == @event.creator_id %>
          <%= link_to "Edit", edit_event_path, class: "button" %>
          <%= link_to "Back", root_path, class: "button" %>
          <%= link_to "Delete", event_path, class: "button", method: :delete, data: { confirm: "Are you sure you want to delete this event?" } %>
        <%# <% elsif current_user.attended_events %>
          <p class="content has-text-centered">You're attending!</p>
          <ul>
            <% @event.user_invites do |user| %>
              <li><%= user.email %></li>    
            <% end %>
          </ul>
        <% else %>
          <%= link_to "RSVP", invitations_path(event_id: @event.id), :method => :post, class: "button" %>
        <% end %>
    </p>
  </div>

app/views/invitations/_form.html.erb
<%= simple_form_for(@invitation) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing Invitation</h1>

<%= render 'form', invitation: @invitation %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invitations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invitation| %>
      <tr>
        <td><%= link_to 'Show', invitation %></td>
        <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
        <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>New Invitation</h1>

<%= render 'form', invitation: @invitation %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if flash[:notice] %>
      <div class="notification global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= notice %></p>
      </div>
    <% end %>


    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Private Events</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div class="navbar-menu">
        <div class="navbar-start">
          <div class="navbar-item">
            <a class="control">
              <% if user_signed_in? %>
                <%= link_to "New Event", new_event_path, class: "button" %>
              <% end%>
            </a>
          </div>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.email, edit_user_registration_path, class: "button" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button" %>
            </p>
            <p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button" %>
            </p>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>